YARD/MeaninglessTag:
  Description: 'Check meaningless tag'
  Enabled: true
  VersionAdded: '0.4.0'

YARD/TagTypeSyntax:
  Description: 'Check syntax for yard tag type'
  Enabled: true
  VersionAdded: '0.5.0'

YARD/CollectionType:
  Description: 'Check collection type syntax'
  Enabled: true
  VersionAdded: '0.5.0'
  # EnforcedStyle: long
  # SupportedStyles:
  #   - long
  #   - short

YARD/MismatchName:
  Description: 'Check @param and @option name and method parameters'
  Enabled: true
  VersionAdded: '0.3.0'
